version: '3'
services:

  db:
    image: postgres:12.2
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=simplerapp
    volumes:
      - ./docker/pg/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    network_mode: host

  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/proxy.conf:/etc/nginx/conf.d/default.conf:ro
    network_mode: host
    command: nginx -g 'daemon off;'